---
- name: kill existing process if any
  shell: >
     ps -ef | grep qdrouterd  | grep -v grep | awk '{print $2}' | xargs kill  
  ignore_errors: yes
  tags: run

- name: enable qdrouterd.service systemd service
  service: state=started enabled=yes name=qdrouterd.service
  
- name: 
  shell: >
     ps -ef | grep qdrouterd  | grep -v grep | awk '{print $2}' | xargs taskset -cp 2,3 
  tags: run

- include: status.yaml