---
- name: kill existing process if any
  shell: >
    ps -ef | grep qdrouterd  | grep -v grep | awk '{print $2}' | xargs kill
  ignore_errors: yes
  tags:
    - start
- name: Enable qdrouterd.service systemd service
  service: state=started enabled=yes name=qdrouterd.service
  tags:
    - start
- name: Pin pid to 2and 3 core
  shell: >
    ps -ef | grep qdrouterd  | grep -v grep | awk '{print $2}' | xargs taskset -cp 2,3
  tags:
    - start
- name: Check if qdrouterd is running
  shell: >
    ps aux | grep qdrouterd | grep -v grep
  ignore_errors: yes
  changed_when: false
  register: service_qdrouterd_status
  tags:
    - status
- name: Report status of qdrouterd
  fail:
    msg: |
      Service qdrouterd is not running.
      Return code from `grep`:
      {{ service_qdrouterd_status.rc }}
  when: service_qdrouterd_status.rc != 0
  tags:
    - status