---
- name: kill existing process if any
  shell: >
    ps -ef | grep qdrouterd  | grep -v grep | awk '{print $2}' | xargs kill
  ignore_errors: yes
  tags:
    - start
- name: Enable qdrouterd.service systemd service
  service: state=started enabled=yes name=qdrouterd.service
  tags:
    - start
- name: Pin pid to 2and 3 core
  shell: >
    ps -ef | grep qdrouterd  | grep -v grep | awk '{print $2}' | xargs taskset -cp 2,3
  tags:
    - start
