---
- name: kill existing process if any
  shell: >
    ps -ef | grep qdrouterd  | grep -v grep | awk '{print $2}' | xargs kill
  ignore_errors: yes
  tags:
    - start
- name: Enable qdrouterd.service systemd service
  service: state=started enabled=yes name=qdrouterd.service
  tags:
    - start
#- name: Pin pid to cores
#  shell: >
#    ps -ef | grep qdrouterd  | grep -v grep | awk '{print $2}' | xargs taskset -ap {{isolcpus}}
#  tags:
#    - start
#- name: Pin pid to cores
#  shell: >
#     taskset -a {{isolcpus}} qdrouterd &
#  tags:
#   - start


