---
- hosts: router
  remote_user: root
  roles:
    - common

- hosts: event_sender
  remote_user: root
  roles:
    - common

- hosts: event_receiver
  remote_user: root
  roles:
    - common

- hosts: traffic_sender
  remote_user: root
  roles:
    - common
    - install-13nodes

- hosts: traffic_receiver
  remote_user: root
  roles:
    - common
    - install-13nodes