---
- hosts: router
  remote_user: root
  roles:
    - { role: setup, tags: [ 'setup' ] }
    - { role: common, tags: [ 'router' ] }
    - { role: install-13nodes, tags: [ 'client' ] }
    - { role: start_routers, tags: [ 'start','status' ] }
- hosts: event_tx
  remote_user: root
  roles:
    - { role: setup, tags: [ 'setup' ] }
    - { role: common, tags: [ 'router' ] }
    - { role: install-13nodes, tags: [ 'client' ] }
    - { role: start_routers, tags: [ 'start','status' ] }
- hosts: event_rx
  remote_user: root
  roles:
    - { role: setup, tags: [ 'setup' ] }
    - { role: common, tags: [ 'router' ] }
    - { role: install-13nodes, tags: [ 'client' ] }
    - { role: start_routers, tags: [ 'start','status'] }
- hosts: traffic_tx
  remote_user: root
  roles:
    - { role: setup, tags: [ 'setup' ] }
    - { role: common, tags: [ 'router' ] }
    - { role: install-13nodes, tags: [ 'client' ] }
    - { role: start_routers, tags: ['start','status'] }
- hosts: traffic_rx
  remote_user: root
  roles:
    - { role: setup, tags: [ 'setup' ] }
    - { role: common, tags: [ 'router' ] }
    - { role: install-13nodes, tags: [ 'client' ] }
    - { role: start_routers, tags: [ 'start','status' ] }