---
- hosts: all
  user: root
  gather_facts: no
  #serial: 1
  pre_tasks:
    - name: ping all hosts  
      ping:
      #when: inventory_hostname not in hostvars[inventory_hostname].groups['ipmi']
      
- hosts: localhost
  gather_facts: yes
  roles:
    - ipmi-check
  vars_files:
    - vars/ipmi.yaml

- hosts: router
  remote_user: root
  roles:
    - { role: setup, tags: [ 'setup' ] }
    - { role: configure, tags: [ 'config' ] }
    - { role: common, tags: [ 'router' ] }
    - { role: install-13nodes, tags: [ 'client' ] }
    - { role: start_routers, tags: [ 'start'] }
    - { role: status, tags: ['status' ] }
- hosts: event_tx
  remote_user: root
  roles:
    - { role: setup, tags: [ 'setup' ] }
    - { role: configure, tags: [ 'config' ] }
    - { role: common, tags: [ 'router' ] }
    - { role: install-13nodes, tags: [ 'client' ] }
    - { role: start_routers, tags: [ 'start'] }
    - { role: status, tags: ['status' ] }
- hosts: event_rx
  remote_user: root
  roles:
    - { role: setup, tags: [ 'setup' ] }
    - { role: configure, tags: [ 'config' ] }
    - { role: common, tags: [ 'router' ] }
    - { role: install-13nodes, tags: [ 'client' ] }
    - { role: start_routers, tags: [ 'start'] }
    - { role: status, tags: ['status' ] }
- hosts: traffic_tx
  remote_user: root
  roles:
    - { role: setup, tags: [ 'setup' ] }
    - { role: configure, tags: [ 'config' ] }
    - { role: common, tags: [ 'router' ] }
    - { role: install-13nodes, tags: [ 'client' ] }
    - { role: start_routers, tags: ['start'] }
    - { role: status, tags: ['status' ] }
- hosts: traffic_rx
  remote_user: root
  roles:
    - { role: setup, tags: [ 'setup' ] }
    - { role: configure, tags: [ 'config' ] }
    - { role: common, tags: [ 'router' ] }
    - { role: install-13nodes, tags: [ 'client' ] }
    - { role: start_routers, tags: [ 'start'] }
    - { role: status, tags: ['status' ] }