---
- hosts: all
  user: root
  gather_facts: False
  #serial: 1
  pre_tasks:
    - name: ping all hosts
      ping:
  tags:
    - ping
    - all
    - setup-ssh
      #when: inventory_hostname not in hostvars[inventory_hostname].groups['ipmi']

- hosts: standalone
  roles:
    - { role: install-client, tags: [ 'proton-client'] }
    - { role: configure, tags: ['config-standalone']}
    - { role: common,tags: ['router']}
    - { role: start_routers, tags: [ 'start'] }
    - { role: status, tags: ['status' ] }
  become: true

- hosts: localhost
  gather_facts: yes
  roles:
    - { role: ipmi-check, tags: [ 'ipmi-check' ] }
    - { role: setup, tags: [ 'setup-ssh' ] }
  vars_files:
    - vars/ipmi.yaml
  tags: ipmi

- hosts: router
  remote_user: root
  roles:
    - { role: affinity, tags: [ 'setup-grub' ] }
    - { role: setup, tags: [ 'setup' ] }
    - { role: configure, tags: [ 'config' ] }
    - { role: common, tags: [ 'router' ] }
    - { role: install-client, tags: [ 'proton-client' ] }
    #- { role: install-13nodes, tags: [ 'client' ] }
    - { role: start_routers, tags: [ 'start'] }
    - { role: status, tags: ['status' ] }
- hosts: event_tx
  remote_user: root
  roles:
    - { role: affinity, tags: [ 'setup-grub' ] }
    - { role: setup, tags: [ 'setup' ] }
    - { role: configure, tags: [ 'config' ] }
    - { role: common, tags: [ 'router' ] }
    - { role: install-client, tags: [ 'proton-client' ] }
    #- { role: install-13nodes, tags: [ 'client' ] }
    - { role: start_routers, tags: [ 'start'] }
    - { role: status, tags: ['status' ] }
- hosts: event_rx
  remote_user: root
  roles:
    - { role: affinity, tags: [ 'setup-grub' ] }
    - { role: setup, tags: [ 'setup' ] }
    - { role: configure, tags: [ 'config' ] }
    - { role: common, tags: [ 'router' ] }
    - { role: install-client, tags: [ 'proton-client' ] }
    #- { role: install-13nodes, tags: [ 'client' ] }
    - { role: start_routers, tags: [ 'start'] }
    - { role: status, tags: ['status' ] }
- hosts: traffic_tx
  remote_user: root
  roles:
    - { role: affinity, tags: [ 'setup-grub' ] }
    - { role: setup, tags: [ 'setup' ] }
    - { role: configure, tags: [ 'config' ] }
    - { role: common, tags: [ 'router' ] }
    - { role: install-client, tags: [ 'proton-client' ] }
    #- { role: install-13nodes, tags: [ 'client' ] }
    - { role: start_routers, tags: ['start'] }
    - { role: status, tags: ['status' ] }
- hosts: traffic_rx
  remote_user: root
  roles:
    - { role: affinity, tags: [ 'setup-grub' ] }
    - { role: setup, tags: [ 'setup' ] }
    - { role: configure, tags: [ 'config' ] }
    - { role: common, tags: [ 'router' ] }
    - { role: install-client, tags: [ 'proton-client' ] }
    #- { role: install-13nodes, tags: [ 'client' ] }
    - { role: start_routers, tags: [ 'start'] }
    - { role: status, tags: ['status' ] }
