---
- name: setup iptables
  shell: >
   iptables -I INPUT -p tcp --dport 5672 -j ACCEPT;
   iptables -I INPUT -p tcp --dport 20002 -j ACCEPT;
   iptables -I INPUT -p tcp --dport 20003 -j ACCEPT;
  tags: config
- name: save iptables
  command: iptables-save
  tags: config