---
- name: clean  of any old proton examples code
  file: name={{ansible_env.HOME}}/proton-examples state=absent force=yes
  tags:
    - proton-client
- name: clone proton-examples code
  git: repo={{ client_ken_base_repo }} version=master accept_hostkey=yes dest={{ansible_env.HOME}}/proton-examples
  tags:
    - proton-client
- name: Install dependency
  action: "{{ ansible_pkg_mgr }} name=qpid-proton-c-devel state=present"
  when: install_proton_from_source|default(false)|bool ==false
  tags:
   - proton-client
- name: clean client
  shell: >
   cd {{ansible_env.HOME}}/proton-examples/latency;
   make -f proton.mk clean;
  tags:
    - proton-client
- name: make client
  shell: >
   cd {{ansible_env.HOME}}/proton-examples/latency;
   make -f proton.mk all;
  tags:
    - proton-client
