---
- name: Check if Apache is running
  shell: ps aux | grep qdrouterd | grep -v grep
  ignore_errors: yes
  changed_when: false
  register: service_qdrouterd_status
  tags: status

- name: Report status of qdrouterd
  fail:
    msg: |
      Service qdrouterd is not running.
      Return code from `grep`:
      {{ service_qdrouterd_status.rc }}
  when: service_qdrouterd_status.rc != 0
  tags: status