---
- name: clean  of any old 13nodes code
  file: name={{ansible_env.HOME}}/13nodes state=absent force=yes
  tags:
    - client
- name: clone 13nodes code
  git: repo={{ client_base_repo }} version=master accept_hostkey=yes dest={{ansible_env.HOME}}/13nodes
  tags:
    - client
- name: Install dependency
  yum: name=qpid-proton-c-devel state=present
  when: install_proton_from_source|default(false)|bool ==false
  tags:
   - client
- name: clean client
  shell: >
   cd {{ansible_env.HOME}}/13nodes/source;
   make -f proton.mk clean;
  tags:
    - client
- name: make client
  shell: >
   cd {{ansible_env.HOME}}/13nodes/source;
   make -f proton.mk all;
  tags:
    - client
